tourism/urls.py
from django.contrib import admin
from django.urls import path,include
# from travelapp.views import BookingListView

app_name = 'travelapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('travelapp.urls')),
]

travelapp/urls.py
from travelapp import views
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

app_name = 'travelapp'

urlpatterns = [
    path('', views.index, name = 'index'),
    #user CRUD urls
    path('create-user/', views.signup, name = 'user_create'),
    path('login-user/', views.user_login, name= 'user_login'),
    path('update-user/' ,views.CustomerUpdateView.as_view(), name = 'user_update'),
    path('logout-user/', views.user_logout, name = 'user_logout'),
    path('detail-user/<pk>/', views.myUserDetailView.as_view(), name = "x" ),
    path('delete-user/', views.deleteuser, name='user_delete'),
    #Booking CRUD
    path('myB/', views.BookingCreateView1,name='booking_create__'),
    path('book-list/update/<pk>/', views.BookingUpdateView.as_view(), name = 'booking_update'),
    path('book-list/', views.BookingListView.as_view(), name='booking_list'),
    path('delete-book/<pk>/', views.BookingDeleteView.as_view(), name='booking_delete'),
    path('book-list/<pk>/',views.booking_detail_view, name= 'booki'),
    path('package/', views.PackageListView.as_view(), name= 'package_list'),
    path('detail-user/', views.customerdetail, name='user_detail'),
    path('user-list/', views.userlist, name='list-user')    

]
urlpatterns+=static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)


    #path('create-payment/', views.PaymentCreateView.as_view(), name = 'payment_create'),
    # path('create-book/', views.BookingCreateView.as_view(), name='booking_create'),
    #path(r'^update/(?p<pk>\d+)/$', views.BookingUpdateView.as_view(), name = 'booking_update'),
    # path('booking/<int:id>/', views.bookView, name = 'booking'),
    # path('list__/', views.booking_list_view, name='list_book'),
        #path('book-list/<pk>/', views.BookingDetailView.as_view(), name='booking_detail'),

travelapp/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
#Create your models here.
class Customers(models.Model):
    customer_name = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)
    customer_address = models.CharField(max_length=100, default = 'Nepal')
    customer_dob = models.DateField(default = '2020/01/23')
    def __str__(self):
        return f'{self.customer_name}'


class Package(models.Model):
    package_name = models.CharField(max_length = 100, primary_key = True)
    created_by  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    package_destination = models.CharField(max_length = 100, unique= True)
    package_number_of_days = models.IntegerField()
    package_description = models.CharField(max_length = 300, null =True)
    package_image = models.ImageField(upload_to = 'package_images')
    per_person_amt = models.IntegerField()
    def __str__(self):
        return self.package_name

class Booking(models.Model):
    # booking_id = models.IntegerField(primary_key = True)
    booking_type = models.CharField(max_length = 200)
    booking_start_date = models.DateField()
    hotel = (('Annapurna',"Hotel Del Annapurna"),('Hyatt','Hyatt regency'),('Malla ','Hotel malla'),('Everest','Hotel Everest'),('Mahakali', 'Hotel Mahakali'))
    booking_hotel = models.CharField(max_length = 200,choices = hotel)
    booking_transport  = models.CharField(max_length = 200, default = 'Bus')
    number_people = models.IntegerField()
    # payment_card_number = models.ForeignKey(Payments, on_delete = models.CASCADE)
    booked_by = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    package_name = models.ForeignKey(Package, on_delete = models.CASCADE)    
    
    def __str__(self):
        return f'{self.booking_type}'
    def get_absolute_url(self):
        return reverse("travelapp:booking_detail", kwargs= {'pk':self.pk})  # 
    
# class Payments(models.Model):
#     # pay_id = models.AutoField(primary_key = True,)
#     modes= (('Visa','Visa'), ('Master','Master Card'), ('American','American Express'), ('Apple','Apple Card'))
#     # payment_holder_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
#     payment_mode = models.CharField(max_length =30, choices= modes)
#     expiry_date = models.DateField()
#     # payment_card_number = models.CharField(max_length=20, primary_key = True)
#     # booking_id = models.ForeignKey(Booking, on_delete = models.CASCADE, null = True)
#     def __str__(self):
#         return self.payment_mode
#     def get_absolute_url(self):
#         return reverse('admin:index')

class Payments(models.Model):
    modes= (('Visa','Visa'), ('Master','Master Card'), ('American','American Express'), ('Apple','Apple Card'),('Esewa', 'Esewa'), ('Khalti','Khalti'),('Bitcoin','Bitcoin'),
    ('PayPal', 'PayPal')
    )
    payment_mode = models.CharField(max_length =30, choices = modes)
    voucher_no = models.CharField(max_length = 20, default = None, null = True)
    booking_id = models.ForeignKey('Booking', on_delete = models.CASCADE, null = True)
    def __str__(self):
        return f'{self.payment_mode}'

travelapp/forms.py
from django.contrib.auth.models import User
from django import forms
from travelapp.models import Customers, User, Payments, Package, Booking
from creditcards.forms import CardNumberField

class CustomerProfileForm(forms.ModelForm):
    customer_address = forms.CharField(required =False, widget = forms.TextInput())
    customer_dob = forms.DateField(required = False, widget = forms.DateInput())
    class Meta():
        model = Customers
        exclude = ('customer_name',)

class CustomerForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class CustomerUpdateForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('username','email')


class PaymentForm(forms.ModelForm):
    #modes= (('Visa','Visa'), ('Master','Master Card'), ('American','American Express'), ('Apple','Apple Card'))
    # payment_mode = forms.CharField(max_length = '30',choices = modes)
    # expiry_date = forms.DateField()
    # payment_card_number = forms.CharField(label = "Enter Debit/Credit Card Number")
    class Meta():
        model = Payments
        exclude = ('booking_id',)

    
class UserDeleteForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [] 

class BookingForm(forms.ModelForm):
    types = (('Travel','Travel Package'), ('Tour','Tour Package'),('Hiking','Hiking Package'),('Trekking','Trekking Package'))
    booking_type = forms.ChoiceField(choices = types, label = 'Choose Your Travelling Model')
    booking_start_date = forms.DateField(label = "Enter Your Starting Date")
    vehicles = (("Bus",'Bus'),('Van','Van'),("Micro Bus",'Micro'),('car','Car'))
    booking_transport = forms.ChoiceField(choices = vehicles, label = "Choose Your Vehicle Type")
    hotel = (('Annapurna',"Hotel Del Annapurna"),('Hyatt','Hyatt regency'),('Malla ','Hotel malla'),('Everest','Hotel Everest'))
    booking_hotel = forms.ChoiceField(choices= hotel, label= "Choose Your Hotel")
    number_people = forms.IntegerField(label = 'Enter Total Number Of People') 
    class Meta():
        model = Booking
        exclude = ('booked_by','')

class BookingUpdateForm(forms.ModelForm):
    types = (('Travel','Travel Package'), ('Tour','Tour Package'),('Hiking','Hiking Package'),('Trekking','Trekking Package'))
    booking_type = forms.ChoiceField(choices = types, label = 'Choose Your Travelling Model', required = False)
    booking_start_date = forms.DateField(label = "Enter Your Starting Date",required = False)
    vehicles = (("Bus",'Bus'),('Van','Van'),("Micro Bus",'Micro'),('car','Car'))
    booking_transport = forms.ChoiceField(choices = vehicles, label = "Choose Your Vehicle Type",required = False)
    hotel = (('Annapurna',"Hotel Del Annapurna"),('Hyatt','Hyatt regency'),('Malla ','Hotel malla'),('Everest','Hotel Everest'),('Mahakali', 'Hotel Mahakali'))
    booking_hotel = forms.ChoiceField(choices= hotel, label= "Choose Your Hotel",required = False)
    number_people = forms.IntegerField(label = 'Enter Total Number Of People',required = False) 
    class Meta():
        model = Booking
        exclude = ('booked_by','package_name','payment-card_number')

travelapp/views.py
from django.shortcuts import render, redirect
from travelapp.models import Customers, Payments, Package, Booking
from travelapp.forms import CustomerForm, CustomerProfileForm,CustomerUpdateForm, PaymentForm, UserDeleteForm, BookingForm,BookingUpdateForm
# For Login Authentication 
from django.urls import reverse,reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login,logout
from django.views.decorators.http import require_http_methods
from django.contrib.auth import logout as auth_logout, get_user_model
from django.contrib.auth.models import User
from django.views.generic import DeleteView, UpdateView, CreateView, DetailView, ListView
from django.utils.decorators import method_decorator


# Create your views here.
def index(request): 
    return render(request, 'travelapp/index.html')
# Customer Creation
def signup(request):
    registered = False
    if request.method == 'POST':
        customer_form = CustomerForm(data= request.POST)
        customerprofile_form = CustomerProfileForm(data = request.POST)
        if customer_form.is_valid() and customerprofile_form.is_valid():
            # customer main -- name, email and password
            customer = customer_form.save()
            customer.set_password(customer.password)
            customer.save()

            # customer new datas --address and date
            customerprofile = customerprofile_form.save(commit = False)
            customerprofile.customer_name = customer
            customerprofile.save()
            registered =True
            return render(request, 'travelapp/login.html')
        else:
            print(customer_form.errors,customerprofile_form.errors)
    else:
        customer_form = CustomerForm()
        customerprofile_form = CustomerProfileForm()
    return render(request, 'travelapp/customers_form.html', {'userform': customer_form, 'customerform':customerprofile_form, 'registered':registered})  

# Login Authentication
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Authentication
        user = authenticate(username=username, password= password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('travelapp:index'))
            else:
                return HttpResponse("Your Account is not active.")
        else:
            print("Login Failed.")
            print("Username: {}  \n Password:{} ".format(username,password))
            return HttpResponse("Invalid Login Details")
    else:
        return render(request, 'travelapp/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('travelapp:index'))

@login_required
def special(request):
    return HttpResponse("You Are SucessFully Logged In!")

# class DeleteCustomerView(DeleteView):
#     success_url = reverse_lazy('travelapp:index')
#     template_name = "travelapp/customer_delete.html"
#     model = User
#     #This is the original form
#     def get_object(self, queryset=None):
#         return self.request.user




@login_required
def deleteuser(request):
    if request.method == 'POST':
        delete_form = UserDeleteForm(request.POST, instance=request.user)
        user = request.user
        user.delete()
        messages.info(request, 'Your account has been deleted.')
        return redirect('travelapp:index')
    else:
        delete_form = UserDeleteForm(instance=request.user)

    context = {
        'delete_form': delete_form
    }

    return render(request, 'travelapp/customer_delete.html', context)

class CustomerUpdateView(UpdateView):
    success_url = reverse_lazy('travelapp:index')
    template_name = "travelapp/customer_update.html"
    model = User
    form_class= CustomerUpdateForm
    def get_object(self, queryset=None):
        return self.request.user

class PaymentCreateView(CreateView):
    template_name = "travelapp/payment_form.html"
    model = Payments
    success_url = reverse_lazy('travelapp:index')
    form_class = PaymentForm
    # @method_decorator(login_required)
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.payment_holder_name  = self.request.user
        #article.save()  # This is redundant, see comments.
        return super(PaymentCreateView, self).form_valid(form)

class PaymentDeleteView(DeleteView):
    success_url = reverse_lazy('travelapp:index')
    template_name = "travelapp/payment_delete.html"
    model = Payments


class CustomerDetailView(DetailView):
    model = Customers
    template_name = 'inventory/item_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CustomerDetailView, self).get_context_data(**kwargs)
        context['username']  = User.objects.filter().order_by(F('username').asc())
        # other code
        return context

# class BookingCreateView(CreateView):
#     model = Booking
#     form_class = BookingForm
#     template_name = 'travelapp/booking_create_form.html'
#     success_url = reverse_lazy('travelapp:booking_list') 
#     def form_valid(self, form):
#         obj = form.save(commit=False)
#         obj.booked_by  = self.request.user
#         #article.save()  # This is redundant, see comments.
#         obj.save()
#         return super(BookingCreateView, self).form_valid(form)

def BookingCreateView1(request):
    if request.method == 'POST':
        registered = False
        Book_form = BookingForm(data = request.POST or None)
        pay_form = PaymentForm(data = request.POST or None)
        if Book_form.is_valid() and pay_form.is_valid():
            # customer main -- name, email and password
            book = Book_form.save(commit = False)
            book.booked_by = request.user
            book.save()
            pay = pay_form.save(commit = False)
            pay.booking_id = book
            pay.save()
            registered = True
            # customer = customer_form.save()
            return redirect(reverse('travelapp:booking_list'))
        else:
            print(Book_form.errors, pay_form.errors)
    else:
        Book_form = BookingForm()
        pay_form = PaymentForm()

        context = {
        # 'delete_form': delete_form, 
        'Bform' : Book_form,
        'Pform' : pay_form
        }
    return render(request, 'travelapp/book_detail.html', context)

class BookingUpdateView(UpdateView):
    model = Booking
    form_class = BookingUpdateForm
    success_url = reverse_lazy('travelapp:booking_list')
    template_name = 'travelapp/booking_update_form.html' 

class BookingListView(ListView):
    model = Booking
    def get_queryset(self):
        return Booking.objects.filter(booked_by=self.request.user)

class BookingDeleteView(DeleteView):
    model = Booking
    queryset = Booking.objects.all()
    success_url = reverse_lazy('travelapp:booking_list')
    template_name  = 'travelapp/booking_delete.html'

class PackageListView(ListView):
    model = Package

class BookingDetailView(DetailView):
    context_object_name = 'booking_detail'
    model = Booking
    template_name = 'travelapp/bookings_detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super(BookingDetailView, self).get_context_data(**kwargs)
    #     context['payment']  = Payments.objects.all()
    #     return context



class myUserDetailView(DetailView):
    model = Customers
    template_name = 'travelapp/customer_detail.html'


def booking_detail_view(request,pk):
    payment_obj = Payments.objects.get(pk=pk)
    booking_obj = Booking.objects.filter(id=payment_obj.id)
    # booking_obj = Booking.objects.get(pk=pk)
    # payment_obj = Payments.objects.filter(booking_id_id= booking_obj)
    context = {'booking':booking_obj,'payment':payment_obj,'pk':pk}
    return render(request, 'travelapp/booking_detail_.html', context=context)

def booking_list_view(request):
    # dictionary for initial data with 
    # field names as keys
    context ={}  
    # add the dictionary during initialization
    context["value"] = Booking.objects.all().order_by("id")
    user = Booking.created_by()
    customer = Customer.objects.get( user = user)
    context['id']=customer
    return render(request, "travelapp/list_book.html", context)

def customerdetail(request):
    context = {}
    context['customer'] = Customers.objects.filter(customer_name = request.user)
    return render(request, "travelapp/customer_detail.html", context)

def userlist(request):
    context = {}
    context['list'] =User.objects.all()
    return render(request, "travelapp/user_list.html", context)

travelapp/templates/travelapp/base_customer_payment.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travel Nepal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/b.css'%}">
</head>
<body>
<!-- navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4"> 
        <a class="base_url_home" href="{% url 'travelapp:index'%}">Travel Nepal   
            <span class="sr-only">(current)</span>  
        </a>   
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">  
            <span class="navbar-toggler-icon"></span>  
        </button>  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">  
            <ul class="navbar-nav mr-auto">  
                {% if user.is_authenticated and user.is_superuser %}    
                <li class="nav-item active">  
                    <a class="nav-link" href="{% url 'travelapp:booking_list'%}">Package Management   
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>
                {% elif user.is_authenticated %}    
                <li class="nav-item active">  
                    <a class="nav-link" href="{% url 'travelapp:booking_list'%}">Booking   
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>
                {% endif %} 
                <li class="nav-item active">  
                    <a class="nav-link" href="{% url 'travelapp:package_list'%}">Packages  
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>  
            </ul>  
            {% if user.is_authenticated and user.is_superuser %}  
            <!-- Admininstration -->
            <ul class= "navbar-nav mr-auto">
                <li class="nav-item active">  
                    <a class="nav-link" href="http://127.0.0.1:8000/admin/travelapp/package/">Create Packages   
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>

                <li class="nav-item active">  
                    <a class="nav-link" href="{% url 'travelapp:user_logout'%}">Logout   
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>  
            </ul>
            {% elif user.is_authenticated %}  
                <!-- Customer  -->
                <ul class= "navbar-nav mr-auto">
                <li class="nav-item active">  
                    <a class="nav-link" href="{% url 'travelapp:user_update'%}">Update Profile   
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>
                <li class="nav-item active">  
                    <a class="nav-link" href="{% url 'travelapp:user_detail'%}">Your Details  
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>
                <li class="nav-item active">  
                    <a class="nav-link" href="{% url 'travelapp:user_delete'%}">Delete Your Profile  
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>
                <li class="nav-item active">  
                    <a class="nav-link" href="{% url 'travelapp:user_logout'%}">Logout   
                        <span class="sr-only">(current)</span>  
                    </a>  
                </li>
            </ul>
            {% else %}
            <!-- Login And Sign Up For All -->
                <a class="btn btn-primary ml-2 mr-2" href="{% url 'travelapp:user_login'%}">Login</a>  
                <a class="btn btn-primary ml-2 mr-2" href=" {% url 'travelapp:user_create'%} ">SignUp</a>  

<!-- Put endif template tagging here -->
            {% endif %}  
        </div>  
    </nav> 
<!-- Up to Here  -->
    {% block body_block%}
    {% endblock%}
</body>
</html>

travelapp/templates/travelapp/booking_delete.html
{% extends "travelapp/base_customer_payment.html"%}
{% block body_block %}
<div class="listView">

    <div>
        <h2> Are you sure you want to delete ? </h2>
        <form  method="post">  
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn btn-primary">
        </form>
    </div>
     <!-- </form> -->
    
</div>
{% endblock %}  

travelapp/templates/travelapp/booking_detail_.html
{% extends "travelapp/base_customer_payment.html"%}
{% block body_block %}

<div class="listView">
    {% if user.is_authenticated and user.is_superuser %}
    <h4> Admin Cannot Book!</h4>
    {% elif user.is_authenticated%}
    <h3>Booking's detail</h3><br>
    {% for i in booking %}
    <h5>
        Booking Start Date: {{ i.booking_start_date }}<br>
        Booking Hotel:{{ i.booking_hotel }}<br>
        Booking Transportation:{{ i.booking_transport }}<br>
        Total Number Of People: {{ i.number_people }}<br>
        Booked User Name:   {{ i.booked_by }}<br>
        Booked Package Name:  {{ i.package_name }}<br>
        {% endfor %}
        Payment Mode:   {{ payment.payment_mode}}<br>
        Payment Vocher: {{ payment.voucher_no}}<br>
        <!-- Advance Amt : {{ payment.advance_amt}} -->
    </h5>
    <br>
    <p><a href="{% url 'travelapp:booking_update' pk=pk%}"class="url_create">Update </a></p>
    <p><a href="{% url 'travelapp:booking_delete' pk=pk%}"class="url_create">Delete</a></p>
    {% else %}
    <h4> Should Login/Sign Up To Acess Booking Previleges!</h4>
    {% endif %}
</div>
{% endblock %}  

travelapp/templates/travelapp/bookings_detail.html
{% extends "travelapp/base_customer_payment.html"%}
{% block body_block %}
<div class="listView">
    <h4> Booking's Detail</h4>
    <h5> Booking Type: {{booking_detail.booking_type}}</h5>
    <h5> Booking Start Date: {{booking_detail.booking_start_date}}</h5>
    <h5> Booking Hotel : {{booking_detail.booking_hotel}}</h5>
    <h5> Booking Transport: {{booking_detail.booking_transport}}</h5>
    <h5> Number Of People: {{booking_detail.number_people}}</h5>
    <h5> Booked By : {{booking_detail.booked_by}}</h5>
    <h5> Booked Package Name: {{booking_detail.package_name}} </h5>
    <h5>{{id.customer_dob}}</h5>
    <p><a href="{% url 'travelapp:booking_update' pk=booking_detail.pk%}">Update </a></p>
    <p><a href="{% url 'travelapp:booking_delete' pk=booking_detail.pk%}">Delete</a></p>
</div>

{% endblock %}  

travelapp/templates/travelapp/customer_delete.html
{% extends "travelapp/base_customer_payment.html"%}
{% block body_block %}
<div class="listView">
<h2>Are you sure you want to delete your Profile ?</h2>
<form method="post" action="{% url 'travelapp:user_delete'%}">  
    {% csrf_token %}  
     <input type="submit" value="Delete Profile!" class="btn btn-primary">  
 </form>
</div>
{% endblock %}  

travelapp/templates/travelapp/customer_detail.html
{% extends "travelapp/base_customer_payment.html"%}
{% block body_block %}
<div class="listView">
    {% if user.is_authenticated and user.is_superuser %}
    <h3> Go to This Section !</h3>
    <p><a href="{% url 'travelapp:list-user' %}" class="url_create">Update </a></p>
    {% elif user.is_authenticated%}
    {% for x in customer%}
    <h3> Your Details</h3><br>
        <h5>customer name: {{x}}</h5><br>
        <h5>customer dob: {{ x.customer_dob}}</h5><br>
        <h5>address : {{x.customer_address}}</h5><br>
        <h5>email: {{x.customer_name.email}}</h5><br>
        <p><a href="{% url 'travelapp:user_update' %}" class="url_create">Update </a></p>
        <p><a href="{% url 'travelapp:user_delete' %}" class="url_create">Delete</a></p>
    {% endfor %}
    {% else %}
    <h3>Please Sign Up/ Login To acess !</h3>
    <a href="{% url 'travelapp:user_create'%}" class="url_create" >Create Account</a>
    <a href="{% url 'travelapp:user_login'%}" class="url_create" >Login </a>
    {% endif%}
</div>
{% endblock %}  


<!-- <div class="listView">
    <h3>
        Name:   {{ object.customer_name}}<br>
        Email:  {{ object.customer_name.email }}<br>
        Address:{{ object.customer_address }}<br>
        Date of Birth :{{object.customer_dob}}<br><br><br>
        
    </h3>
</div>
 -->

travelapp/templates/travelapp/customers_form.html
{% extends "travelapp/base_customer_payment.html"%}
{% block body_block %}
{% load crispy_forms_tags %}
    <div class="signupOne">
        <div class="title">Travel Nepal</div>
        <div class="sub-title">Your Favourite Travel Hub.</div><br>
        <div class="stepone"> Fill The Form </div>
        <div class="stepone"> Create Your Profile ! </div>
        <div class="form">
            <form method="POST"enctype="multipart/form-data">
                <div class="row">                  
                    <div class="row_q">
                        {%csrf_token%}
                        {{ userform|crispy }}
                    </div>
                    <div class="row_q">
                        {{ customerform|crispy }}
                    </div>
            </form>     
            <div class="login">
                 <input type="submit" class="btn btn-primary" value="Sign Up">  
                <div class="user">Already a user?</div>
                <a href="{% url 'travelapp:user_create'%}" class ="base_url_home">  Login</a>
            </div> 
    </div>
{% endblock %}

travelapp/templates/travelapp/login.html
{% extends "travelapp/base_customer_payment.html"%}
{% block body_block %}

    <div class="signupOne">
        <div class="title">Travel Nepal</div>
        <div class="sub-title">Your Favourite Travel Hub.</div><br>
        <div class="stepone"> Please Login </div>
        <div class="form">
            <form method="POST" action="{% url 'travelapp:user_login' %}">
            {% csrf_token %}
            <div class="row">
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Enter Password">
            </div>
            <div class="login_page_login">
            <input type="submit" class="btn btn-primary" value="Login">    
            </div>  
            <div class="login">
                <div class="user">New To Website ?</div>
                <a href="{% url 'travelapp:user_create'%}" class="base_url_home ">  Sign In </a>
            </div> 
        </form>
    </div>
{% endblock %}

travelapp/templates/travelapp/package_list.html
{% extends "travelapp/base_customer_payment.html"%}
{% block body_block %}
{% for post in object_list %}
<div class="container">
    <img src="{{ post.package_image.url}}" alt="Package" class="imag">
    <div class="overlay">
      <div class="texte">
          <h2>{{post.package_name}}</h2>
          <p>{{post.package_description}}</p>
          <h4> Total Days: {{post.package_number_of_days}}</h4>
          <h5>Package Destination: <br>{{post.package_destination}}</h5>
          <h5>Per Person Amount: $ {{post.per_person_amt}}</h5>
          {% if user.is_authenticated %}
          <a href="{% url 'travelapp:booking_create__'%}"></a>
          <a href="{% url 'travelapp:booking_list'%}" id="book_create_submit">Book Now</a>
          {% else %}
          <h5>Please Sign Up/ Login for Booking!</h5>
          <a href="{% url 'travelapp:user_create'%}" id="book_create_submit">Create Account</a>
          {% endif%}
        </div>
    </div>
  </div>
{% endfor%}
{% endblock %}  